title: campus-concert
description: An application for student musicians to find other musicians and concerts
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions